from __future__ import annotations

from typing import Any, Protocol


class RuntimeAdapter(Protocol):
    def DescribeRuntime(self) -> Any: ...
    def StartRun(self, request: Any) -> Any: ...
    def AdvanceRun(self, request: Any) -> Any: ...
    def SuspendRun(self, request: Any) -> Any: ...
    def ResumeRun(self, request: Any) -> Any: ...
    def CancelRun(self, request: Any) -> Any: ...
    def InspectRun(self, request: Any) -> Any: ...


class ContextBuildPort(Protocol):
    def __call__(self, request: Any) -> Any: ...


class ModelStepPort(Protocol):
    def __call__(self, request: Any) -> Any: ...


class ToolIntentPort(Protocol):
    def __call__(self, request: Any) -> Any: ...


class HandoffPort(Protocol):
    def __call__(self, request: Any) -> Any: ...


class TelemetryPort(Protocol):
    def EmitTrace(self, record: Any) -> Any: ...
    def EmitMetric(self, points: list[Any]) -> Any: ...
    def EmitLog(self, records: list[Any]) -> Any: ...
    def EmitAudit(self, record: Any) -> Any: ...
